title: Dilvan Güler # your name (or website title) here
logo: "/images/82770845_2457497947821987_7367178791765934080_n.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome!<br>
  I am a second year engineering student at KTH Royal Institute of Technology in Stockholm, Sweden.
  I am studying a Degree Programme in Information and Communication Technology. 
  
  <br><br>
  You can watch my work and projects I've contributed to here!
  <br><br>
  <a href="https://www.linkedin.com/in/dilvanguler/">View My LinkedIn Profile!</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
